### ISSUE TITLE
Switch to using enum as a suffix instead of a prefix in filenames

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Helper#21]
I'd like to consider switching from EnumSoundID and EnumTechID to SoundIDEnum and TechIDEnum. I think it reads a little easier on the filesystem and in source code includes. 

Not a big deal if others prefer enum as a prefix instead. If this is the case, BuildingBayEnum could be switched to match the prefix style.

**Comment by DanRStevens** [comment]
My preference is to use a prefix, since the natural sort order makes the enums easier to find, and kind of separates the source code for enum definitions from other source code.

We may need someone to be a tie-breaker on this decision.

We also need to keep in mind that name changes break source code compatibility. If we go changing old names, we'll need to provide a migration path.

**Comment by Brett208** [comment]
Is changing a subheader filename a breaking change? I would expect a user to include OP2Helper.h, not the subheaders individually.

In the meantime, let's change the new enum to use the prefix in its filename. Lacking a consensus to change, it is probably better to be consistent with the established terminology. Also, this is a pretty minor point, so don't think we need to spend a lot of calories debating it.

**Comment by DanRStevens** [comment]
Ahh, maybe ignore my last point. A filename change is not a problem. If the name of the enum itself changes, that's a different matter. For some reason I was thinking the name of the enum exactly matched the filename.
